info:
  component: Zuul Server

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000000

ribbon.ReadTimeout = 10000000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    gui:
      path: /**
      url: http://10.28.2.166:8080/
    backend:
      path: /api/**
      url: http://10.28.2.166:8081/
    crawler:
      path: /crawler/**
      url: http://10.28.2.166:8082/
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
