info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    gui:
      path: /**
      url: http://localhost:8080/
    backend:
      path: /api/**
      url: http://localhost:8081/
    crawler:
      path: /crawler/**
      url: http://localhost:8082/
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
